### ISSUE TITLE
关于在前端代码中暴漏 api key 的问题

### ISSUE THREAD

**Issue by KevinHu-1024** [zhangxin840/tomato5#24]
我最近也正在写一个Serverless应用，用于内网的技术分享管理。今天刚看到您的项目，获益良多。但我最近一直纠结于，如果使用静态页面来进行鉴权、db访问等功能，那势必会在前端代码中暴漏两者的api key，可能会引发安全问题，最后还是被迫采用了一个server，绕了一下。我看咱们项目也是暴漏了 api key，请问后期如何解决？

**Comment by zhangxin840** [comment]
你好，这里的API Key是项目的唯一标识。前端需要用这个Key来定位项目。前端暴漏Key就像暴漏接口URL一样是没有风险的。常用的GA，Sentry等服务也会用到Api Key，跟这个作用是一样的。拿Sentry来说，它有public和private两段不同的key，对于Node层，会加上private key，对于browser，就只有public key。Firebase相当于只用public key，没有风险。

**Comment by zhangxin840** [comment]
另外我很好奇你是怎么做转发的，是否起到了翻墙效果？我下一步想做中转解决墙的问题。

**Comment by KevinHu-1024** [comment]
哦，我明白了，原来一直没想清楚这个 key 的问题。

我这的转发不是转发了 firebase 的鉴权请求。而是因为没弄明白 key 的安全性，转而采用自建 github token 服务器来实现 github 认证登录（之前之所以采用 firebase 就是想用它的 github 鉴权）。

至于墙的问题，我们也在探索中，国内有野狗在做类似 firebase 的服务。google 12 月分的开发者大会有讲 firebase 的内容，不知会上会不会有人提出墙的问题。

**Comment by zhangxin840** [comment]
可以加QQ Firebase群联络：436388406

**Comment by KevinHu-1024** [comment]
✔️ 已加
